version: '3.7'

services:
  
  webserver:
    image: mariort/php-nginx:1.0
    container_name: ${WEBSERVER_CONTAINER_NAME}
    volumes:
      - .:/www
    ports:
      - "8000:80"
    networks: 
      - default

networks:
  default:
    name: ${DOCKER_DEFAULT_NETWORK}